# Generated by Django 4.0.4 on 2022-08-03 12:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Host',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('mac_addr', models.CharField(blank=True, max_length=40, null=True)),
                ('hostname', models.CharField(blank=True, max_length=100, null=True)),
            ],
        ),
    ]
